[[releases]]
version = "0.2.0"
date = "2026-01-31"
refs = [
    "WI-2026-01-31-003",
    "WI-2026-01-31-004",
    "WI-2026-01-31-005",
]

[[releases]]
version = "0.1.1"
date = "2026-01-31"
refs = [
    "WI-2026-01-31-001",
    "WI-2026-01-31-002",
]

[[releases]]
version = "0.1.0"
date = "2026-01-30"
refs = [
    "WI-2026-01-25-001",
    "WI-2026-01-25-002",
    "WI-2026-01-26-001",
    "WI-2026-01-26-002",
    "WI-2026-01-26-003",
    "WI-2026-01-27-001",
    "WI-2026-01-28-001",
    "WI-2026-01-28-002",
    "WI-2026-01-29-001",
    "WI-2026-01-29-002",
    "WI-2026-01-29-003",
    "WI-2026-01-29-004",
    "WI-2026-01-29-005",
    "WI-2026-01-29-006",
    "WI-2026-01-29-007",
    "WI-2026-01-29-008",
    "WI-2026-01-29-009",
    "WI-2026-01-29-010",
    "WI-2026-01-29-011",
    "WI-2026-01-29-012",
    "WI-2026-01-29-013",
    "WI-2026-01-29-014",
    "WI-2026-01-29-015",
    "WI-2026-01-29-016",
    "WI-2026-01-29-017",
    "WI-2026-01-29-018",
    "WI-2026-01-29-019",
    "WI-2026-01-29-020",
    "WI-2026-01-29-021",
    "WI-2026-01-29-022",
    "WI-2026-01-29-023",
    "WI-2026-01-29-024",
    "WI-2026-01-29-025",
    "WI-2026-01-29-026",
    "WI-2026-01-29-027",
    "WI-2026-01-30-001",
    "WI-2026-01-30-002",
    "WI-2026-01-30-003",
    "WI-2026-01-30-004",
    "WI-2026-01-30-005",
    "WI-2026-01-30-006",
    "WI-2026-01-30-007",
    "WI-2026-01-30-008",
    "WI-2026-01-30-009",
    "WI-2026-01-30-010",
    "WI-2026-01-30-011",
    "WI-2026-01-30-012",
    "WI-2026-01-30-013",
]
